### ISSUE TITLE
Optimise/Merge Duplicate textures error

### ISSUE THREAD

**Issue by Soul-XV2** [LazyBone152/XV2-Tools#33] opened 2022-01-15 16:03 UTC
Using EEPKOrg version 0.9.3 and up to 0.9.6 all have this same issue.
When using "Optimise textures", I'm given an error (or it just goes to "Not Responding..." and exits)
The directory is set, doing this with BTL_AURA loaded from the CPK or from my game's modded directory both result in the error, same with no mods. I've tested on every version from 0.9.3 to 0.9.6 with no success. Not entirely sure if it's still user error or a tool issue itself but troubleshooting it didn't give me any solutions.
Edit: This is on 1.16, not 1.17
The error log:
![image](https://user-images.githubusercontent.com/97798418/149628727-e82344b0-7cb2-402a-81fd-6e551f27d0fc.png)
![image](https://user-images.githubusercontent.com/97798418/149628494-432535d5-fa3b-44b9-aa49-1fdecc3dfd32.png)

**Comment by LazyBone152** [comment] 2022-01-15 23:46
Can you go into the texture viewer (click on the PBIND tab -> then the big texture button to the right) and see if any of the textures actually load?

**Comment by Soul-XV2** [comment] 2022-01-15 23:52
Seems like most of them are there
![image](https://user-images.githubusercontent.com/97798418/149641449-dab8933c-5546-4816-834b-0b06abd0992c.png)

**Comment by LazyBone152** [comment] 2022-01-16 00:11
[EEPK Organiser test.zip](https://github.com/LazyBone152/XV2-Tools/files/7876125/EEPK.Organiser.test.zip)
Retry with this build and tell me what error pops up. It wont fix anything itself since it's just modified to display a few error messages during the merge process, which should hopefully tell me whats going wrong.

**Comment by LazyBone152** [comment] 2022-01-16 00:12
Also, what OS are you on? IIRC some of the DDS loading code is dependent on that.

**Comment by Soul-XV2** [comment] 2022-01-16 00:29
I'm using Windows x64. The test build came up with this error when optimising 
![image](https://user-images.githubusercontent.com/97798418/149642498-ecfbb7c2-ceb0-4db7-8c9e-e97abe42bed4.png)

![image](https://user-images.githubusercontent.com/97798418/149642481-fb76f45f-2140-4263-937d-1de581e2cf70.png)

**Comment by LazyBone152** [comment] 2022-01-16 01:05
Windows 10?

Based on that error the issue is what I thought it was. The merge works fine but the resulting texture cant be loaded... an issue with the way textures are currently loaded probably.

**Comment by Soul-XV2** [comment] 2022-01-16 01:22
So the issue is mostly the output and not the actual merging of textures, it sounds like a relatively simple fix (coming from someone who's never touched code ever lmao)

**Comment by LazyBone152** [comment] 2022-01-16 01:39
If only.... 

I'll probably need to replace the texture loading library with something different (and better). The current one has always given me trouble one way or another. 

As a quick hacky fix I might be able to just disable the texture reloading and the merge will work without issue for you. But you probably wont be able to do anymore merges on the eepk after that since the textures wont load. If you want to try that then give this build a shot, but definitely back up your VFX folder first.

[EEPK Organiser test.zip](https://github.com/LazyBone152/XV2-Tools/files/7876217/EEPK.Organiser.test.zip)
.

**Comment by Soul-XV2** [comment] 2022-01-16 01:41
Alright, thanks. Hopefully this whole deal fixes the tool for the better, and makes future updates easier rather than harder. I appreciate the help

**Closed** 2022-01-16 01:54 UTC
Labels: bug, enhancement

**Comment by LazyBone152** [comment] 2022-01-16 01:58
There is one last thing to try though its a bit of a long shot. Tell me if this build works at all.

[EEPK Organiser test.zip](https://github.com/LazyBone152/XV2-Tools/files/7876229/EEPK.Organiser.test.zip)

**Comment by Soul-XV2** [comment] 2022-01-16 02:02
The test build you sent before this one seems to work, merged things together with no issue, 99 to 3 on vanilla EEPK. The last build you sent gives the DdsImage error again

**Comment by LazyBone152** [comment] 2022-01-16 02:04
And the textures load fine in game?

**Comment by Soul-XV2** [comment] 2022-01-16 02:09
Once I optimise textures and try to save the file, it errors. EEPKOrg really does not like me lol
![image](https://user-images.githubusercontent.com/97798418/149644572-5a8f12a2-f3a8-463d-a2a3-3590cd2c4393.png)

![image](https://user-images.githubusercontent.com/97798418/149644565-23f71c6d-b1dd-4e0e-99b9-a6890f441f74.png)

**Comment by LazyBone152** [comment] 2022-01-16 02:25
Okay that is just a silly mistake on my end. When I commented out the lines for reloading the texture that also included the name.

[EEPK Organiser test.zip](https://github.com/LazyBone152/XV2-Tools/files/7876248/EEPK.Organiser.test.zip)

**Comment by Soul-XV2** [comment] 2022-01-16 02:34
It worked! Merged 99 into 3 and saved successfully without any issues. Though, like you said, reopening and trying to optimise the same EEPK again does give the original "object reference" error so it's a one use only fix. Still, it's significantly better than it not working at all lol
