### ISSUE TITLE
ACE: Can't paste CUEs

### ISSUE THREAD

**Issue by UnleashedGH** [LazyBone152/XV2-Tools#12] opened 2021-04-13 18:53 UTC
Error when pasting a CUE (either from another or self ACB)

System.Runtime.InteropServices.COMException: 'Data on clipboard is invalid (Exception from HRESULT: 0x800401D3 (CLIPBRD_E_BAD_DATA))'

on ACB_FILE.cs line 444

a bit off-topic but this information from the debugger, as ACE also wasn't writing ace_log.txt even after running on Administrator

**Comment by LazyBone152** [comment] 2021-04-30 10:16
Seems to be caused by the ACB_SequenceBlock and ACB_Block classes which are unfinished and missing the [Serializable] attribute.

These 2 classes aren't used for anything but I guess they are still included in the serialization anyway.

**Comment by LazyBone152** [comment] 2021-05-01 04:41
Should be fixed now.

**Closed by LazyBone152** 2021-05-01 04:41 UTC
