### ISSUE TITLE
EEPK glare issue on V1.03

### ISSUE THREAD

**Issue by LOLDJ23** [LazyBone152/XV2-Tools#53] opened 2022-05-23 13:45 UTC
Seems the new version has an issue with the glare value when saving imported files. I tested with a backup file i did a month ago and it works fine but when importing the EMOs with new version they have wrong glare values.
What i did was:
deleting effect IDs
deleting PBINDs
deleting textures
deleting materials
deleting LIGHTs
deleting EMOs
saving and deleting the files from hard disk clicking "Yes" option
closed the EEPK and re-opened it
importing files from my backup and save
tested ingame, wrong glare
the backup works because putting it inside the game has no wrong glare values on effects
i tested this on Vegito's spirit sword (ultimate) and vegito's barrier (evasive) but the issue appears also on focus flash (vegeta blue super skill)
[vegito's barrier EMM.zip](https://github.com/LazyBone152/XV2-Tools/files/8755035/vegito.s.barrier.EMM.zip)
in this folder u have the corrupted version and the backup one (XMLs)

**Comment by LazyBone152** [comment] 2022-07-15 18:43
This should be fixed with the next update (in both EEPK Organiser and the installer).

The issue was caused by some values being incorrectly not saved back, but I've now added some code so that all the values that the materials are originally read with are always saved.

**Closed** 2022-07-17 22:12 UTC
